CREATE TABLESPACE firstData DATAFILE 'D:\app\alfo3-20\oradata\orcl11\first01.dbf' SIZE 10M;
ALTER TABLESPACE firstData ADD DATAFILE 'D:\app\alfo3-20\oradata\orcl11\first01.dbf' SIZE 1M;
ALTER TABLESPACE firstData ADD DATAFILE 'D:\app\alfo3-20\oradata\orcl11\first02.dbf' SIZE 10M;
ALTER DATABASE DATAFILE 'D:\app\alfo3-20\oradata\orcl11\first01.dbf' RESIZE 20M;
ALTER DATABASE DATAFILE 'D:\app\alfo3-20\oradata\orcl11\first02.dbf' AUTOEXTEND ON NEXT 1M MAXSIZE 20M;
DROP TABLESPACE firstData INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE javaData DATAFILE 'D:\app\alfo3-20\oradata\orcl11\app_data.dbf' SIZE 20M AUTOEXTEND ON NEXT 3M MAXSIZE 500M;
CREATE USER javauser IDENTIFIED BY java1234 DEFAULT TABLESPACE javaData TEMPORARY TABLESPACE temp;
GRANT CONNECT, RESOURCE TO javauser;

